import test from 'node:test';import assert from 'node:assert/strict';import {buildLearningMemory,searchLearningMemory} from '../src/memory.js';import worker from '../src/worker.js';
const runs=()=>[{id:'r1',title:'Activation research',evidence:[{id:'f1',source:'support',text:'New users cannot finish onboarding',topicId:'t1',sentiment:{label:'negative'},detection:{primaryIntent:'bug'}}],experiments:[{id:'e1',opportunityId:'o1',evidenceIds:['f1'],opportunitySnapshot:{title:'Improve onboarding',topicId:'t1'},plan:{hypothesis:'A checklist improves onboarding activation',primaryMetric:'Activation'},decision:{id:'d1',outcome:'ship',rationale:'The prospective result passed review',reviewer:'PM',decidedAt:'2026-08-01T00:00:00.000Z'},outcomeReviews:[{createdAt:'2026-09-01T00:00:00.000Z',monitorId:'m1',analysis:{status:'sustained',relativeChange:.1,targetMet:true}}]}]}];
test('builds evidence-linked decision cards',()=>{const memory=buildLearningMemory(runs());assert.equal(memory.summary.decisions,1);assert.equal(memory.summary.monitoringCoverage,1);assert.deepEqual(memory.cards[0].evidenceIds,['f1']);assert.equal(memory.cards[0].decisionId,'d1')});
test('finds prior learning with explainable weighted matches',()=>{const result=searchLearningMemory(buildLearningMemory(runs()),'onboarding activation');assert.equal(result.total,1);assert.ok(result.results[0].relevance>0);assert.ok(result.results[0].matches.some(x=>x.field==='hypothesis'))});
test('filters by human decision and monitored outcome',()=>{const memory=buildLearningMemory(runs());assert.equal(searchLearningMemory(memory,'onboarding',{outcome:'ship',status:'sustained'}).total,1);assert.equal(searchLearningMemory(memory,'onboarding',{outcome:'reject'}).total,0)});
test('rejects unbounded inputs and empty queries',()=>{assert.throws(()=>buildLearningMemory(Array(51).fill(runs()[0])),/at most 50/);assert.throws(()=>searchLearningMemory(buildLearningMemory(runs()),' '),/2–200/)});
const request=(path,input,token='secret')=>new Request(`https://test${path}`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify(input)});
test('authenticated worker indexes and searches runs',async()=>{const response=await worker.fetch(request('/api/search',{runs:runs(),query:'activation',filters:{}}),{API_TOKEN:'secret'});assert.equal(response.status,200);assert.equal((await response.json()).total,1)});
test('worker fails closed without configuration or authorization',async()=>{assert.equal((await worker.fetch(request('/api/index',{runs:runs()}),{})).status,503);assert.equal((await worker.fetch(request('/api/index',{runs:runs()},'bad'),{API_TOKEN:'secret'})).status,401)});
