const required=(value,name,max=500)=>{if(typeof value!=='string'||!value.trim()||value.length>max)throw new Error(`${name} must contain 1–${max} characters`);return value.trim()};
const timestamp=(value,name)=>{if(typeof value!=='string'||!/^\d{4}-\d{2}-\d{2}T/.test(value)||Number.isNaN(Date.parse(value)))throw new Error(`${name} must be an ISO timestamp`);return new Date(value).toISOString()};
const integer=(value,name,min,max)=>{if(!Number.isInteger(value)||value<min||value>max)throw new Error(`${name} must be an integer from ${min} to ${max}`);return value};
const validate=(report,collection,project)=>{if(report?.schemaVersion!=='1.0.0'||!Array.isArray(report[collection]))throw new Error(`Provide a Project ${project} report`)};

export function verifyExceptionExits(runs,exceptionsReport,verificationReport,input={}){
  if(!Array.isArray(runs)||runs.length>50)throw new Error('Provide an array of at most 50 product runs');validate(exceptionsReport,'registers',26);validate(verificationReport,'monitors',25);
  if(!Array.isArray(input.reviews)||!input.reviews.length||input.reviews.length>50)throw new Error('Provide 1–50 exit reviews');
  const registers=new Map(exceptionsReport.registers.map(register=>[register.id,register]));const monitors=new Map(verificationReport.monitors.map(monitor=>[monitor.id,monitor]));const ids=new Set();const reviews=[];
  for(const[index,raw]of input.reviews.entries()){
    const id=required(raw.id,`Review ${index+1} id`,80);if(ids.has(id))throw new Error('Review IDs must be unique');ids.add(id);
    const registerId=required(raw.registerId,`${id} registerId`,80);const register=registers.get(registerId);if(!register)throw new Error(`Unknown exception register: ${registerId}`);
    const exceptionId=required(raw.exceptionId,`${id} exceptionId`,80);const exception=register.exceptions.find(item=>item.id===exceptionId);if(!exception)throw new Error(`Unknown exception: ${exceptionId}`);
    const verificationMonitorId=required(raw.verificationMonitorId,`${id} verificationMonitorId`,80);const monitor=monitors.get(verificationMonitorId);if(!monitor)throw new Error(`Unknown verification monitor: ${verificationMonitorId}`);const asOf=timestamp(raw.asOf,`${id} asOf`);
    const observationWindowDays=integer(raw.observationWindowDays,`${id} observationWindowDays`,1,365);const observedDays=integer(raw.observedDays,`${id} observedDays`,0,365);
    if(!Array.isArray(raw.effectivenessTests)||!raw.effectivenessTests.length||raw.effectivenessTests.length>50)throw new Error(`${id} must contain 1–50 effectiveness tests`);
    const testIds=new Set();const effectivenessTests=raw.effectivenessTests.map((test,testIndex)=>{const testId=required(test.id,`${id} test ${testIndex+1} id`,80);if(testIds.has(testId))throw new Error(`${id} test IDs must be unique`);testIds.add(testId);const verifiedAt=timestamp(test.verifiedAt,`${id} ${testId} verifiedAt`);if(Date.parse(verifiedAt)>Date.parse(asOf))throw new Error(`${id} ${testId} cannot be verified after asOf`);return{id:testId,owner:required(test.owner,`${id} ${testId} owner`,120),criterion:required(test.criterion,`${id} ${testId} criterion`,500),passed:typeof test.passed==='boolean'?test.passed:(()=>{throw new Error(`${id} ${testId} passed must be boolean`)})(),evidence:required(test.evidence,`${id} ${testId} evidence`,1000),verifiedAt}});
    const residualRisk=required(raw.residualRisk,`${id} residualRisk`,20);if(!['low','medium','high','critical'].includes(residualRisk))throw new Error(`${id} residualRisk is invalid`);
    const approvals=(raw.approvals??[]).map((approval,approvalIndex)=>{const role=required(approval.role,`${id} approval ${approvalIndex+1} role`,40).toLowerCase();const decision=required(approval.decision,`${id} approval ${approvalIndex+1} decision`,20);if(!['approved','rejected'].includes(decision))throw new Error(`${id} approval decision is invalid`);return{role,reviewer:required(approval.reviewer,`${id} approval ${approvalIndex+1} reviewer`,120),decision,reviewedAt:timestamp(approval.reviewedAt,`${id} approval ${approvalIndex+1} reviewedAt`)}});if(new Set(approvals.map(item=>item.role)).size!==approvals.length)throw new Error(`${id} approval roles must be unique`);
    const reviewRaw=raw.review??{};const decision=required(reviewRaw.decision,`${id} decision`,20);if(!['close','extend','escalate'].includes(decision))throw new Error(`${id} decision is invalid`);const review={reviewer:required(reviewRaw.reviewer,`${id} reviewer`,120),decision,rationale:required(reviewRaw.rationale,`${id} rationale`,1000),reviewedAt:timestamp(reviewRaw.reviewedAt,`${id} reviewedAt`)};if(Date.parse(review.reviewedAt)>Date.parse(asOf))throw new Error(`${id} review cannot occur after asOf`);
    const target=exception.targetType==='check'?monitor.checks?.find(check=>check.id===exception.targetId):monitor.obligations?.find(item=>item.id===exception.targetId);const targetResolved=exception.targetType==='check'?Boolean(target?.passed&&!monitor.failedChecks?.includes(exception.targetId)):Boolean(target&&target.status==='completed'&&target.evidenceComplete&&!target.overdue);
    const remediation=monitor.obligations?.find(item=>item.id===exception.remediationObligationId);const requiredRoles=['product','governance',...(['high','critical'].includes(residualRisk)?['risk']:[])];const reviewers=approvals.map(item=>item.reviewer.toLowerCase());
    const checks=[
      {id:'active-exception',passed:exception.status==='active_exception',detail:exception.status},
      {id:'lineage-match',passed:register.governancePackId===monitor.governancePackId&&register.portfolioItemId===monitor.portfolioItemId,detail:`register ${register.governancePackId}; monitor ${monitor.governancePackId}`},
      {id:'target-resolved',passed:targetResolved,detail:`${exception.targetType} ${exception.targetId}`},
      {id:'remediation-complete',passed:Boolean(remediation&&remediation.status==='completed'&&remediation.evidenceComplete&&!remediation.overdue),detail:remediation?`${remediation.id}: ${remediation.status}`:'missing'},
      {id:'effectiveness-evidence',passed:effectivenessTests.every(test=>test.passed),detail:`${effectivenessTests.filter(test=>test.passed).length}/${effectivenessTests.length} passed`},
      {id:'observation-window',passed:observedDays>=observationWindowDays,detail:`${observedDays}/${observationWindowDays} days`},
      {id:'required-approvals',passed:requiredRoles.every(role=>approvals.some(item=>item.role===role&&item.decision==='approved'))&&!approvals.some(item=>item.decision==='rejected'),detail:`required: ${requiredRoles.join(', ')}`},
      {id:'review-separation',passed:Date.parse(review.reviewedAt)>=Date.parse(exception.requestedAt)&&review.reviewer.toLowerCase()!==exception.requester.toLowerCase()&&!reviewers.includes(exception.requester.toLowerCase())&&new Set(reviewers).size===reviewers.length,detail:`exception requester ${exception.requester}; exit reviewer ${review.reviewer}`},
      {id:'approval-timing',passed:approvals.every(item=>Date.parse(item.reviewedAt)<=Date.parse(asOf)&&Date.parse(item.reviewedAt)>=Date.parse(exception.requestedAt)),detail:`as of ${asOf}`},
    ];
    const failedChecks=checks.filter(check=>!check.passed).map(check=>check.id);const status=decision==='close'?(failedChecks.length?'blocked_close':'verified_closed'):'action_required';reviews.push({id,registerId,exceptionId,verificationMonitorId,governancePackId:register.governancePackId,portfolioItemId:register.portfolioItemId,title:register.title,evidenceIds:[...(register.evidenceIds??[])],asOf,observationWindowDays,observedDays,residualRisk,effectivenessTests,approvals,review,checks,failedChecks,status});
  }
  return{schemaVersion:'1.0.0',summary:{reviews:reviews.length,verifiedClosed:reviews.filter(item=>item.status==='verified_closed').length,blockedClose:reviews.filter(item=>item.status==='blocked_close').length,actionRequired:reviews.filter(item=>item.status==='action_required').length,failedEffectivenessTests:reviews.flatMap(item=>item.effectivenessTests).filter(test=>!test.passed).length},reviews,method:'deterministic exception-state, lineage, target-resolution, remediation, effectiveness, observation-window, approval, and separation checks; the report never closes an exception or changes a product control'};
}
