import test from 'node:test';
import assert from 'node:assert/strict';
import {stressPortfolio} from '../src/stress.js';

const runs = () => [{id:'run-1',title:'Q4',ranking:{portfolio:{selected:['a','b']},ranked:[{id:'a',title:'Activation',effort:3,score:8,dependencies:[],evidenceIds:['f1']},{id:'b',title:'Retention',effort:2,score:7,dependencies:['a'],evidenceIds:['f2']}]}}];
const strategy = () => ({objectives:[{id:'growth',title:'Growth',minShare:.4,maxShare:.7},{id:'retention',title:'Retention',minShare:.3,maxShare:.6}],mappings:[{runId:'run-1',opportunityId:'a',objectiveId:'growth'},{runId:'run-1',opportunityId:'b',objectiveId:'retention'}]});

test('reports a resilient baseline with lineage',()=>{const result=stressPortfolio(runs(),strategy(),{capacity:5,scenarios:[{id:'base'}]});assert.equal(result.status,'resilient');assert.equal(result.summary.meanResilienceScore,100);assert.equal(result.portfolioItems[0].portfolioItemId,'run-1:a');assert.deepEqual(result.portfolioItems[0].evidenceIds,['f1'])});
test('detects capacity loss',()=>{const result=stressPortfolio(runs(),strategy(),{capacity:5,scenarios:[{id:'loss',capacityFactor:.6}]});assert.equal(result.scenarios[0].status,'critical');assert.equal(result.scenarios[0].capacityOverrun,2);assert.equal(result.status,'exposed')});
test('detects unavailable dependencies',()=>{const result=stressPortfolio(runs(),strategy(),{capacity:5,scenarios:[{id:'dependency',unavailablePortfolioItemIds:['run-1:a']}]});assert.deepEqual(result.scenarios[0].dependencyFailures,[{portfolioItemId:'run-1:b',dependencyPortfolioItemId:'run-1:a'}]);assert.equal(result.scenarios[0].atRiskItems.length,2)});
test('applies effort multipliers deterministically',()=>{const input={capacity:6,scenarios:[{id:'effort',effortMultipliers:[{portfolioItemId:'run-1:b',multiplier:1.5}]}]};const first=stressPortfolio(runs(),strategy(),input),second=stressPortfolio(runs(),strategy(),input);assert.deepEqual(first,second);assert.equal(first.scenarios[0].usedCapacity,6)});
test('finds the weakest scenario',()=>{const result=stressPortfolio(runs(),strategy(),{capacity:5,scenarios:[{id:'base'},{id:'loss',capacityFactor:.5}]});assert.equal(result.summary.weakestScenarioId,'loss');assert.equal(result.summary.scenarios,2)});
test('rejects unmapped, unknown and unbounded inputs',()=>{const bad=strategy();bad.mappings.pop();assert.throws(()=>stressPortfolio(runs(),bad,{capacity:5,scenarios:[{id:'base'}]}),/requires an objective mapping/);assert.throws(()=>stressPortfolio(runs(),strategy(),{capacity:5,scenarios:[{id:'bad',unavailablePortfolioItemIds:['missing']}]}),/unknown portfolio items/);assert.throws(()=>stressPortfolio(runs(),strategy(),{capacity:5,scenarios:new Array(13).fill({id:'x'})}),/1–12/)});
test('requires run scope for ambiguous mappings',()=>{const second=runs()[0];second.id='run-2';const legacy=strategy();legacy.mappings=legacy.mappings.map(({runId,...mapping})=>mapping);assert.throws(()=>stressPortfolio([runs()[0],second],legacy,{capacity:10,scenarios:[{id:'base'}]}),/ambiguous across runs/)});
