import test from 'node:test';
import assert from 'node:assert/strict';
import {buildDecisionProvenancePacks,canonicalize,sha256} from '../src/provenance.js';

const reports={assumptions:{schemaVersion:'1.0.0',assumptions:[{id:'a',statement:'Assumption'}]},readiness:{schemaVersion:'1.0.0',releases:[{id:'rel',status:'ready'}]},adoption:{schemaVersion:'1.0.0',journeys:[{id:'j',completionRate:1}]},lifecycle:{schemaVersion:'1.0.0',plans:[{id:'p',status:'ready'}]},sunset:{schemaVersion:'1.0.0',snapshots:[{id:'s',status:'ready'}]},outcomes:{schemaVersion:'1.0.0',reviews:[{id:'o',snapshotId:'s',planId:'p',journeyId:'j',releaseId:'rel',portfolioItemId:'run:opp',title:'Legacy flow',status:'closed',reviewedAt:'2027-03-01T00:00:00Z',evidenceIds:['f'],shipDecisionIds:['d'],assumptionIds:['a']}]}};
const pack=(overrides={})=>({id:'g',outcomeReviewId:'o',generatedAt:'2027-03-02T00:00:00Z',owner:'Records owner',purpose:'Preserve a reviewable product-decision record.',classification:'confidential',retentionDays:365,approvals:['product','engineering','governance'].map((role,index)=>({role,reviewer:`Reviewer ${index}`,decision:'approved',reviewedAt:'2027-03-03T00:00:00Z'})),review:{author:'Pack author',certifier:'Independent certifier',decision:'certify',rationale:'The lineage and controls are complete.',reviewedAt:'2027-03-03T00:00:00Z'},...overrides});

test('canonicalization is stable across object key order',()=>assert.equal(canonicalize({b:2,a:1}),canonicalize({a:1,b:2})));
test('SHA-256 is stable and changes with content',async()=>{assert.equal(await sha256({a:1}),await sha256({a:1}));assert.notEqual(await sha256({a:1}),await sha256({a:2}))});
test('certifies a complete pack and preserves lineage',async()=>{const x=await buildDecisionProvenancePacks([],reports,{packs:[pack()]});assert.equal(x.summary.certified,1);assert.deepEqual(x.packs[0].evidenceIds,['f']);assert.equal(x.packs[0].artifacts.length,7);assert.equal(x.packs[0].packDigest.length,64)});
test('builds a linked digest chain',async()=>{const x=await buildDecisionProvenancePacks([],reports,{packs:[pack()]});const a=x.packs[0].artifacts;assert.equal(a[0].previousDigest,null);assert.equal(a[1].previousDigest,a[0].digest);assert.equal(x.packs[0].chainHead,a.at(-1).digest)});
test('blocks certification when upstream outcome is not closed',async()=>{const altered=structuredClone(reports);altered.outcomes.reviews[0].status='action_required';const x=await buildDecisionProvenancePacks([],altered,{packs:[pack()]});assert.ok(x.packs[0].failedChecks.includes('upstream-closed'))});
test('blocks missing authoritative artifacts',async()=>{const altered=structuredClone(reports);altered.readiness.releases=[];const x=await buildDecisionProvenancePacks([],altered,{packs:[pack()]});assert.ok(x.packs[0].failedChecks.includes('artifact-coverage'))});
test('requires independent reviewers',async()=>{const x=await buildDecisionProvenancePacks([],reports,{packs:[pack({review:{author:'Same',certifier:'Same',decision:'certify',rationale:'No separation.',reviewedAt:'2027-03-03T00:00:00Z'}})]});assert.ok(x.packs[0].failedChecks.includes('review-separation'))});
test('requires product, engineering, and governance approval',async()=>{const x=await buildDecisionProvenancePacks([],reports,{packs:[pack({approvals:[]})]});assert.ok(x.packs[0].failedChecks.includes('required-approvals'))});
test('enforces classification-specific retention',async()=>{const x=await buildDecisionProvenancePacks([],reports,{packs:[pack({classification:'restricted',retentionDays:365})]});assert.ok(x.packs[0].failedChecks.includes('retention-policy'))});
test('keeps correction and archive choices action-required',async()=>{for(const decision of ['needs_correction','archive']){const p=pack();p.review.decision=decision;const x=await buildDecisionProvenancePacks([],reports,{packs:[p]});assert.equal(x.packs[0].status,'action_required')}});
test('rejects malformed reports, duplicates, and unknown outcomes',async()=>{await assert.rejects(()=>buildDecisionProvenancePacks([],{}, {packs:[pack()]}),/Project 18/);await assert.rejects(()=>buildDecisionProvenancePacks([],reports,{packs:[pack(),pack()]}),/unique/);await assert.rejects(()=>buildDecisionProvenancePacks([],reports,{packs:[pack({outcomeReviewId:'x'})]}),/Unknown/)});
