import { deduplicate, normalizeRecord } from "../public/feedback.js";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"content-type","Access-Control-Allow-Methods":"GET,POST,OPTIONS"};
const buckets=new Map();
const json=(data,status=200,headers={})=>Response.json(data,{status,headers:{...cors,...headers}});
function limited(request,limit=60){const ip=request.headers.get("CF-Connecting-IP")||"local",window=Math.floor(Date.now()/60000),key=`${ip}:${window}`,count=(buckets.get(key)||0)+1;buckets.set(key,count);return count>limit}
async function hash(value){const digest=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value));return[...new Uint8Array(digest)].map(x=>x.toString(16).padStart(2,"0")).join("")}
async function prepare(record,index=0){const item=normalizeRecord(record,index);if(!item)return null;const canonical=item.text.toLowerCase().replace(/[^a-z0-9 ]/g,"").replace(/\s+/g," ").trim();return{...item,schemaVersion:"1.0",fingerprint:await hash(canonical),metadata:record.metadata||{}}}
async function store(db,records,jobId){if(!db)return{stored:records.length,duplicates:0,persistence:"ephemeral"};let stored=0,duplicates=0;for(const x of records){const r=await db.prepare(`INSERT OR IGNORE INTO feedback_events (id,schema_version,text,source,customer,created_at,sentiment,intent,fingerprint,metadata,ingestion_job_id) VALUES (?,?,?,?,?,?,?,?,?,?,?)`).bind(x.id,x.schemaVersion,x.text,x.source,x.customer,x.createdAt,x.sentiment,x.intent,x.fingerprint,JSON.stringify(x.metadata),jobId).run();r.meta.changes?stored++:duplicates++}return{stored,duplicates,persistence:"d1"}}
async function processPayload(env,payload){const prepared=(await Promise.all(payload.records.map(prepare))).filter(Boolean),unique=deduplicate(prepared),result=await store(env.DB,unique,payload.jobId);if(env.DB)await env.DB.prepare("UPDATE ingestion_jobs SET status=?,accepted=?,duplicates=?,completed_at=CURRENT_TIMESTAMP WHERE id=?").bind("completed",result.stored,result.duplicates+prepared.length-unique.length,payload.jobId).run();return{...result,rejected:payload.records.length-prepared.length}}
async function route(request,env){const url=new URL(request.url);if(request.method==="OPTIONS")return new Response(null,{headers:cors});if(url.pathname==="/api/health")return json({status:"ok",service:"feedback-collector",schemaVersion:"1.0",storage:env.DB?"d1":"browser"});if(url.pathname.startsWith("/api/")&&limited(request))return json({error:"Rate limit exceeded",retryAfter:60},429,{"Retry-After":"60"});
 if(url.pathname==="/api/feedback"&&request.method==="POST"){let body;try{body=await request.json()}catch{return json({error:"Request must contain valid JSON"},400)}const records=Array.isArray(body)?body:Array.isArray(body.records)?body.records:[body];if(records.length>1000)return json({error:"Maximum batch size is 1,000"},413);const jobId=crypto.randomUUID();if(env.DB)await env.DB.prepare("INSERT INTO ingestion_jobs (id,source,status,received) VALUES (?,?,?,?)").bind(jobId,body.source||"api",env.INGESTION_QUEUE?"queued":"processing",records.length).run();const payload={jobId,records};if(env.INGESTION_QUEUE){await env.INGESTION_QUEUE.send(payload);return json({jobId,status:"queued",received:records.length},202)}return json({jobId,status:"completed",received:records.length,...await processPayload(env,payload)},201)}
 if(url.pathname==="/api/feedback"&&request.method==="GET"){if(!env.DB)return json({data:[],notice:"D1 is not bound; browser storage remains available."});const limit=Math.min(Number(url.searchParams.get("limit"))||100,500),source=url.searchParams.get("source"),q=source?env.DB.prepare("SELECT * FROM feedback_events WHERE source=? ORDER BY created_at DESC LIMIT ?").bind(source,limit):env.DB.prepare("SELECT * FROM feedback_events ORDER BY created_at DESC LIMIT ?").bind(limit),r=await q.all();return json({data:r.results,count:r.results.length})}
 if(url.pathname.startsWith("/api/jobs/")&&request.method==="GET"){if(!env.DB)return json({error:"Job tracking requires D1"},503);const job=await env.DB.prepare("SELECT * FROM ingestion_jobs WHERE id=?").bind(url.pathname.split("/").pop()).first();return job?json(job):json({error:"Job not found"},404)}
 if(url.pathname==="/api/export"&&request.method==="GET"){if(!env.DB)return json({error:"Export requires D1"},503);const r=await env.DB.prepare("SELECT * FROM feedback_events ORDER BY created_at ASC LIMIT 10000").all(),body=r.results.map(row=>JSON.stringify({...row,metadata:JSON.parse(row.metadata||"{}")})).join("\n");return new Response(body,{headers:{...cors,"Content-Type":"application/x-ndjson","Content-Disposition":"attachment; filename=feedback-events.jsonl"}})}return env.ASSETS.fetch(request)}
export default{fetch:(request,env)=>route(request,env).catch(error=>json({error:"Internal ingestion error",requestId:crypto.randomUUID(),detail:error.message},500)),async queue(batch,env){for(const message of batch.messages){try{await processPayload(env,message.body);message.ack()}catch(error){if(message.attempts<3)message.retry({delaySeconds:2**message.attempts});else{if(env.DB)await env.DB.prepare("UPDATE ingestion_jobs SET status=?,error=?,completed_at=CURRENT_TIMESTAMP WHERE id=?").bind("failed",error.message,message.body.jobId).run();message.ack()}}}}};
