const required=(value,name,max=300)=>{if(typeof value!=='string'||!value.trim()||value.length>max)throw new Error(`${name} must contain 1–${max} characters`);return value.trim()};
const iso=(value,name)=>{const parsed=new Date(value);if(typeof value!=='string'||Number.isNaN(parsed.valueOf()))throw new Error(`${name} must be an ISO date`);return parsed.toISOString()};

function selectedItems(runs){if(!Array.isArray(runs)||runs.length>50)throw new Error('Provide an array of at most 50 product runs');const items=new Map();for(const run of runs){if(!run?.id||!run.ranking)continue;const selected=new Set(run.ranking.portfolio?.selected??[]);for(const item of run.ranking.ranked??[]){if(!selected.has(item.id))continue;const experiments=(run.experiments??[]).filter(experiment=>experiment.opportunityId===item.id);items.set(`${run.id}:${item.id}`,{portfolioItemId:`${run.id}:${item.id}`,runId:run.id,runTitle:run.title,opportunityId:item.id,title:item.title,evidenceIds:[...(item.evidenceIds??[])],experimentIds:experiments.map(x=>x.id),decisionIds:experiments.flatMap(x=>x.decision?.id?[x.decision.id]:[]),outcomeReviewIds:experiments.flatMap(x=>(x.outcomeReviews??[]).map(y=>y.id))})}}return items}

function action(value,index,reviewedAt){const id=required(value.id,`Action ${index+1} id`,80);const status=value.status??'open';if(!['open','in_progress','closed','cancelled'].includes(status))throw new Error(`${id} has an invalid status`);const dueAt=iso(value.dueAt,`${id} dueAt`);return{id,description:required(value.description,`${id} description`,500),owner:required(value.owner,`${id} owner`,120),dueAt,status,overdue:!['closed','cancelled'].includes(status)&&new Date(dueAt)<new Date(reviewedAt)}}

export function reviewInvestments(runs,benefitReport,input={}){
  if(benefitReport?.schemaVersion!=='1.0.0'||!Array.isArray(benefitReport.benefits))throw new Error('Provide a Project 16 benefits report');
  if(!Array.isArray(input.reviews)||!input.reviews.length||input.reviews.length>100)throw new Error('Provide 1–100 investment reviews');
  const items=selectedItems(runs),seen=new Set();
  const reviews=input.reviews.map((raw,index)=>{const id=required(raw.id,`Review ${index+1} id`,80);if(seen.has(id))throw new Error('Review IDs must be unique');seen.add(id);const portfolioItemId=required(raw.portfolioItemId,`${id} portfolioItemId`,240);const item=items.get(portfolioItemId);if(!item)throw new Error(`Unknown selected portfolio item: ${portfolioItemId}`);const benefits=benefitReport.benefits.filter(x=>x.portfolioItemId===portfolioItemId);const reviewedAt=iso(raw.reviewedAt,`${id} reviewedAt`);const decision=raw.decision;if(!['continue','correct','close','escalate'].includes(decision))throw new Error(`${id} decision must be continue, correct, close, or escalate`);const actions=(raw.actions??[]).map((x,i)=>action(x,i,reviewedAt));if(actions.length>20)throw new Error(`${id} has more than 20 actions`);if(['correct','escalate'].includes(decision)&&!actions.length)throw new Error(`${id} requires at least one corrective action`);const checks=[
    {id:'evidence-lineage',passed:item.evidenceIds.length>0,detail:`${item.evidenceIds.length} evidence records retained`},
    {id:'decision-lineage',passed:item.decisionIds.length>0,detail:`${item.decisionIds.length} reviewed decisions retained`},
    {id:'benefit-profile',passed:benefits.length>0,detail:`${benefits.length} benefits linked`},
    {id:'benefits-measured',passed:benefits.length>0&&benefits.every(x=>x.actual!==null),detail:`${benefits.filter(x=>x.actual!==null).length}/${benefits.length} measured`},
    {id:'no-overdue-measurement',passed:benefits.every(x=>x.status!=='overdue'),detail:`${benefits.filter(x=>x.status==='overdue').length} overdue`},
    {id:'attribution-reviewed',passed:benefits.length>0&&benefits.every(x=>Boolean(x.attributionNote)),detail:'Attribution notes are review statements, not causal proof'}
  ];const failedChecks=checks.filter(x=>!x.passed).map(x=>x.id);return{...item,id,reviewer:required(raw.reviewer,`${id} reviewer`,120),reviewedAt,decision,rationale:required(raw.rationale,`${id} rationale`,2000),assuranceStatus:failedChecks.length?'incomplete':'complete',checks,failedChecks,benefitIds:benefits.map(x=>x.id),benefitStatuses:benefits.map(x=>({id:x.id,status:x.status,progress:x.progress,unit:x.unit})),actions,openActions:actions.filter(x=>!['closed','cancelled'].includes(x.status)).length,overdueActions:actions.filter(x=>x.overdue).length}});
  return{schemaVersion:'1.0.0',summary:{reviews:reviews.length,complete:reviews.filter(x=>x.assuranceStatus==='complete').length,incomplete:reviews.filter(x=>x.assuranceStatus==='incomplete').length,openActions:reviews.reduce((n,x)=>n+x.openActions,0),overdueActions:reviews.reduce((n,x)=>n+x.overdueActions,0),decisions:Object.fromEntries(['continue','correct','close','escalate'].map(x=>[x,reviews.filter(y=>y.decision===x).length]))},reviews,method:'deterministic post-implementation assurance checks plus a named human decision; no automatic go/kill decision or causal inference'}
}
