const DAY=86_400_000;
function required(value,name,max=500){if(typeof value!=='string'||!value.trim()||value.length>max)throw new Error(`${name} must contain 1–${max} characters`);return value.trim();}
function timestamp(value,name){if(typeof value!=='string'||!/^\d{4}-\d{2}-\d{2}T/.test(value)||Number.isNaN(Date.parse(value)))throw new Error(`${name} must be an ISO timestamp`);return new Date(value).toISOString();}
function integer(value,name,min,max){if(!Number.isInteger(value)||value<min||value>max)throw new Error(`${name} must be an integer from ${min} to ${max}`);return value;}
const daysBetween=(start,end)=>Math.floor((Date.parse(end)-Date.parse(start))/DAY);
const check=(id,passed,detail)=>({id,passed,detail});

function normalizeCauses(raw,reviewId){
  if(!Array.isArray(raw)||!raw.length||raw.length>10)throw new Error(`${reviewId} requires 1–10 contributing conditions`);
  const ids=new Set();
  return raw.map((item,index)=>{const id=required(item.id,`${reviewId} condition ${index+1} id`,80);if(ids.has(id))throw new Error(`${reviewId} condition IDs must be unique`);ids.add(id);const category=required(item.category,`${id} category`,30);if(!['process','tooling','data','coordination','policy'].includes(category))throw new Error(`${id} category is invalid`);return{id,category,condition:required(item.condition,`${id} condition`,1000),evidence:required(item.evidence,`${id} evidence`,1000)};});
}
function normalizeLessons(raw,reviewId){
  if(!Array.isArray(raw)||!raw.length||raw.length>20)throw new Error(`${reviewId} requires 1–20 lessons`);
  const ids=new Set();return raw.map((item,index)=>{const id=required(item.id,`${reviewId} lesson ${index+1} id`,80);if(ids.has(id))throw new Error(`${reviewId} lesson IDs must be unique`);ids.add(id);return{id,statement:required(item.statement,`${id} statement`,1000),evidence:required(item.evidence,`${id} evidence`,1000)};});
}
function normalizeActions(raw,reviewId,asOf){
  if(!Array.isArray(raw)||!raw.length||raw.length>30)throw new Error(`${reviewId} requires 1–30 corrective actions`);
  const ids=new Set();return raw.map((item,index)=>{const id=required(item.id,`${reviewId} action ${index+1} id`,80);if(ids.has(id))throw new Error(`${reviewId} action IDs must be unique`);ids.add(id);const type=required(item.type,`${id} type`,20);if(!['prevent','detect','mitigate'].includes(type))throw new Error(`${id} type is invalid`);const priority=required(item.priority,`${id} priority`,4);if(!['p0','p1','p2','p3'].includes(priority))throw new Error(`${id} priority is invalid`);const status=required(item.status,`${id} status`,20);if(!['open','completed','waived'].includes(status))throw new Error(`${id} status is invalid`);const dueAt=timestamp(item.dueAt,`${id} dueAt`);const evidence=status==='open'?'':required(item.evidence,`${id} evidence`,1000);return{id,type,priority,status,owner:required(item.owner,`${id} owner`,120),trackingId:required(item.trackingId,`${id} trackingId`,120),successMeasure:required(item.successMeasure,`${id} successMeasure`,500),dueAt,evidence,overdue:status==='open'&&Date.parse(dueAt)<Date.parse(asOf)};});
}
function normalizeApprovals(raw,reviewId,recoveryReviewer,reviewedAt){
  if(!Array.isArray(raw)||raw.length!==3)throw new Error(`${reviewId} requires Product, Operations, and Governance approvals`);
  const roles=new Set();const reviewers=new Set();return raw.map((item,index)=>{const role=required(item.role,`${reviewId} approval ${index+1} role`,30).toLowerCase();if(!['product','operations','governance'].includes(role)||roles.has(role))throw new Error(`${reviewId} approval roles must be unique and required`);roles.add(role);const reviewer=required(item.reviewer,`${reviewId} ${role} reviewer`,120);if(reviewers.has(reviewer)||reviewer===recoveryReviewer)throw new Error(`${reviewId} approvals must be independent`);reviewers.add(reviewer);const decision=required(item.decision,`${reviewId} ${role} decision`,20);if(!['approved','rejected'].includes(decision))throw new Error(`${reviewId} approval decision is invalid`);const approvedAt=timestamp(item.approvedAt,`${reviewId} ${role} approvedAt`);if(Date.parse(approvedAt)>Date.parse(reviewedAt))throw new Error(`${reviewId} approvals cannot follow review`);return{role,reviewer,decision,approvedAt};});
}

function assess(raw,context){
  const id=required(raw.id,'incident learning review id',80);const policyRecoveryReviewId=required(raw.policyRecoveryReviewId,`${id} policyRecoveryReviewId`,80);const recovery=context.recoveries.get(policyRecoveryReviewId);if(!recovery)throw new Error(`${id} must reference a Project 37 recovery review`);
  const publishedAt=timestamp(raw.publishedAt,`${id} publishedAt`);if(Date.parse(publishedAt)<Date.parse(recovery.review.reviewedAt)||Date.parse(publishedAt)>Date.parse(context.asOf))throw new Error(`${id} publication must follow recovery review and not exceed asOf`);
  const conditions=normalizeCauses(raw.contributingConditions,id);const lessons=normalizeLessons(raw.lessons,id);const actions=normalizeActions(raw.actions,id,context.asOf);
  const reentry=raw.reentry??{};const startsAt=timestamp(reentry.startsAt,`${id} reentry startsAt`);const freezeUntil=timestamp(raw.freezeUntil,`${id} freezeUntil`);if(Date.parse(startsAt)<Date.parse(context.asOf))throw new Error(`${id} reentry cannot start before asOf`);
  const decision=required(raw.review?.decision,`${id} review decision`,30);if(!['approve_reentry','continue_freeze','escalate'].includes(decision))throw new Error(`${id} review decision is invalid`);const reviewedAt=timestamp(raw.review?.reviewedAt,`${id} review reviewedAt`);if(Date.parse(reviewedAt)<Date.parse(publishedAt)||Date.parse(reviewedAt)>Date.parse(context.asOf))throw new Error(`${id} review must follow publication and not exceed asOf`);
  const approvals=normalizeApprovals(raw.approvals,id,recovery.review.reviewer,reviewedAt);const publicationDays=daysBetween(recovery.review.reviewedAt,publishedAt);const coolingDays=daysBetween(recovery.review.reviewedAt,startsAt);
  const scope=Array.isArray(recovery.scope)?recovery.scope:[];if(!Array.isArray(reentry.scope)||!reentry.scope.length||reentry.scope.some(value=>!scope.includes(value)))throw new Error(`${id} reentry scope must be a non-empty subset of recovered scope`);
  const critical=actions.filter(item=>['p0','p1'].includes(item.priority));const checks=[
    check('verified-recovery',recovery.status==='verified_recovery'&&recovery.review?.decision==='close_reversion','Project 37 must verify and close recovery.'),
    check('timely-publication',publicationDays<=context.maximumReviewDays,`Published in ${publicationDays} days; allowed ${context.maximumReviewDays}.`),
    check('evidence-backed-conditions',conditions.every(item=>item.evidence),'Every contributing system condition has evidence.'),
    check('evidence-backed-lessons',lessons.every(item=>item.evidence),'Every lesson has supporting evidence.'),
    check('balanced-actions',actions.some(item=>item.type==='prevent')&&actions.some(item=>item.type==='detect'),'At least one preventive and one detective action are required.'),
    check('critical-actions-complete',critical.length>0&&critical.every(item=>item.status==='completed'&&item.evidence),'Every P0/P1 action must be completed with evidence.'),
    check('no-overdue-actions',actions.every(item=>!item.overdue),'No corrective action may be overdue.'),
    check('cooling-period',coolingDays>=context.minimumCoolingDays&&Date.parse(startsAt)>=Date.parse(freezeUntil),`Re-entry waits ${coolingDays} days and respects the declared freeze.`),
    check('recovered-baseline',required(reentry.baselineVersion,`${id} baselineVersion`,40)===recovery.recoveredVersion,`Re-entry must start from recovered version ${recovery.recoveredVersion}.`),
    check('safety-controls',reentry.rollbackAcknowledged===true&&reentry.monitoringAcknowledged===true,'Re-entry must acknowledge rollback and monitoring controls.'),
    check('independent-approval',approvals.every(item=>item.decision==='approved'),'Product, Operations, and Governance must independently approve.'),
  ];
  const allPassed=checks.every(item=>item.passed);
  return{id,policyRecoveryReviewId,policyEffectivenessReviewId:recovery.policyEffectivenessReviewId,rolloutId:recovery.rolloutId,proposalId:recovery.proposalId,outcomeReviewId:recovery.outcomeReviewId,experimentId:recovery.experimentId,policyId:recovery.policyId,recoveredVersion:recovery.recoveredVersion,publishedAt,publicationDays,freezeUntil,coolingDays,summary:required(raw.summary,`${id} summary`,1000),impact:required(raw.impact,`${id} impact`,1000),contributingConditions:conditions,lessons,actions,reentry:{owner:required(reentry.owner,`${id} reentry owner`,120),hypothesis:required(reentry.hypothesis,`${id} reentry hypothesis`,1000),baselineVersion:reentry.baselineVersion,scope:reentry.scope,startsAt,rollbackAcknowledged:reentry.rollbackAcknowledged,monitoringAcknowledged:reentry.monitoringAcknowledged},approvals,checks,status:decision==='approve_reentry'?(allPassed?'ready_for_reentry':'blocked_reentry'):'action_required',review:{reviewer:required(raw.review.reviewer,`${id} review reviewer`,120),decision,rationale:required(raw.review.rationale,`${id} review rationale`,1000),reviewedAt}};
}

export function controlPlanningPolicyReentry(runs,recoveryReport,input={}){
  if(!Array.isArray(runs)||runs.length>50)throw new Error('Provide an array of at most 50 product runs');if(recoveryReport?.schemaVersion!=='1.0.0'||!Array.isArray(recoveryReport.policyRecoveryReviews))throw new Error('Provide a Project 37 planning policy recovery report');
  const asOf=timestamp(input.asOf,'asOf');if(Date.parse(recoveryReport.asOf)>Date.parse(asOf))throw new Error('Project 37 report occurs after asOf');const maximumReviewDays=integer(input.maximumReviewDays,'maximumReviewDays',1,30);const minimumCoolingDays=integer(input.minimumCoolingDays,'minimumCoolingDays',1,90);if(!Array.isArray(input.reviews)||!input.reviews.length||input.reviews.length>50)throw new Error('Provide 1–50 incident learning reviews');
  const context={asOf,maximumReviewDays,minimumCoolingDays,recoveries:new Map(recoveryReport.policyRecoveryReviews.map(item=>[item.id,item]))};const ids=new Set();const sources=new Set();const reviews=input.reviews.map(raw=>{const id=required(raw.id,'incident learning review id',80);if(ids.has(id))throw new Error('Incident learning review IDs must be unique');ids.add(id);const source=required(raw.policyRecoveryReviewId,`${id} policyRecoveryReviewId`,80);if(sources.has(source))throw new Error('Each recovery may have only one incident learning review');sources.add(source);return assess(raw,context);});
  const summary=reviews.reduce((result,item)=>{result[item.status]++;return result;},{ready_for_reentry:0,blocked_reentry:0,action_required:0});return{schemaVersion:'1.0.0',asOf,sourcePolicyRecoveryReviewIds:reviews.map(item=>item.policyRecoveryReviewId),sourcePolicyEffectivenessReviewIds:reviews.map(item=>item.policyEffectivenessReviewId),sourcePolicyRolloutIds:reviews.map(item=>item.rolloutId),sourcePolicyChangeIds:reviews.map(item=>item.proposalId),sourceOutcomeReviewIds:reviews.map(item=>item.outcomeReviewId),sourcePolicyExperimentIds:reviews.map(item=>item.experimentId),status:summary.blocked_reentry?'blocked_reentry':summary.action_required?'action_required':'ready_for_reentry',summary:{reviews:reviews.length,...summary},incidentLearningReviews:reviews,method:'deterministic recovery-lineage, publication-timeliness, evidence, preventive/detective action, critical-action, overdue-action, cooling-period, recovered-baseline, safety-control, and independent-approval checks; this controller never lifts a freeze, starts an experiment, changes policy, assigns blame, or proves causality'};
}
