const required=(value,name,max=500)=>{if(typeof value!=='string'||!value.trim()||value.length>max)throw new Error(`${name} must contain 1–${max} characters`);return value.trim()};const timestamp=(value,name)=>{if(typeof value!=='string'||!/^\d{4}-\d{2}-\d{2}T/.test(value)||Number.isNaN(Date.parse(value)))throw new Error(`${name} must be an ISO timestamp`);return new Date(value).toISOString()};const integer=(value,name,min,max)=>{if(!Number.isInteger(value)||value<min||value>max)throw new Error(`${name} must be an integer from ${min} to ${max}`);return value};const days=(a,b)=>(Date.parse(b)-Date.parse(a))/86_400_000;const validate=(report,key,project)=>{if(report?.schemaVersion!=='1.0.0'||!Array.isArray(report[key]))throw new Error(`Provide a Project ${project} report`)};
export function monitorRecurrence(runs,exitReport,monitorReport,input={}){
  if(!Array.isArray(runs)||runs.length>50)throw new Error('Provide an array of at most 50 product runs');validate(exitReport,'reviews',27);validate(monitorReport,'monitors',25);if(!Array.isArray(input.surveillance)||!input.surveillance.length||input.surveillance.length>50)throw new Error('Provide 1–50 surveillance reviews');
  const exits=new Map(exitReport.reviews.map(item=>[item.id,item]));const monitors=new Map(monitorReport.monitors.map(item=>[item.id,item]));const ids=new Set();const surveillance=[];
  for(const[index,raw]of input.surveillance.entries()){
    const id=required(raw.id,`Surveillance ${index+1} id`,80);if(ids.has(id))throw new Error('Surveillance IDs must be unique');ids.add(id);const exitReviewId=required(raw.exitReviewId,`${id} exitReviewId`,80);const exit=exits.get(exitReviewId);if(!exit)throw new Error(`Unknown exit review: ${exitReviewId}`);const asOf=timestamp(raw.asOf,`${id} asOf`);const minimumSnapshots=integer(raw.minimumSnapshots,`${id} minimumSnapshots`,1,24);const maximumCadenceDays=integer(raw.maximumCadenceDays,`${id} maximumCadenceDays`,1,365);
    if(!Array.isArray(raw.monitorIds)||!raw.monitorIds.length||raw.monitorIds.length>24||new Set(raw.monitorIds).size!==raw.monitorIds.length)throw new Error(`${id} monitorIds must contain 1–24 unique IDs`);
    const snapshots=raw.monitorIds.map(value=>{const monitor=monitors.get(required(value,`${id} monitorId`,80));if(!monitor)throw new Error(`Unknown recurrence monitor: ${value}`);return monitor}).sort((a,b)=>Date.parse(a.asOf)-Date.parse(b.asOf));
    if(snapshots.some(item=>Date.parse(item.asOf)<=Date.parse(exit.asOf)||Date.parse(item.asOf)>Date.parse(asOf)))throw new Error(`${id} snapshots must follow the exit and not exceed asOf`);
    const results=snapshots.map(item=>{const target=exit.targetType==='check'?item.checks?.find(check=>check.id===exit.targetId):item.obligations?.find(obligation=>obligation.id===exit.targetId);const targetResolved=exit.targetType==='check'?Boolean(target?.passed&&!item.failedChecks?.includes(exit.targetId)):Boolean(target&&target.status==='completed'&&target.evidenceComplete&&!target.overdue);const remediation=item.obligations?.find(obligation=>obligation.id===exit.remediationObligationId);return{monitorId:item.id,asOf:item.asOf,lineageMatch:item.governancePackId===exit.governancePackId&&item.portfolioItemId===exit.portfolioItemId,targetResolved,remediationMaintained:Boolean(remediation&&remediation.status==='completed'&&remediation.evidenceComplete&&!remediation.overdue),monitorStatus:item.status,recurred:!targetResolved}});
    const dates=[exit.asOf,...snapshots.map(item=>item.asOf)];const maximumObservedGap=Math.max(...dates.slice(1).map((date,i)=>days(dates[i],date)));const reviewRaw=raw.review??{};const decision=required(reviewRaw.decision,`${id} decision`,20);if(!['keep_closed','reopen','escalate'].includes(decision))throw new Error(`${id} decision is invalid`);const review={reviewer:required(reviewRaw.reviewer,`${id} reviewer`,120),decision,rationale:required(reviewRaw.rationale,`${id} rationale`,1000),reviewedAt:timestamp(reviewRaw.reviewedAt,`${id} reviewedAt`)};if(Date.parse(review.reviewedAt)>Date.parse(asOf))throw new Error(`${id} review cannot occur after asOf`);
    const checks=[{id:'verified-exit',passed:exit.status==='verified_closed',detail:exit.status},{id:'snapshot-coverage',passed:snapshots.length>=minimumSnapshots,detail:`${snapshots.length}/${minimumSnapshots}`},{id:'lineage-continuity',passed:results.every(item=>item.lineageMatch),detail:`${results.filter(item=>item.lineageMatch).length}/${results.length}`},{id:'target-stable',passed:results.every(item=>item.targetResolved),detail:`${results.filter(item=>item.recurred).length} recurrences`},{id:'remediation-maintained',passed:results.every(item=>item.remediationMaintained),detail:`${results.filter(item=>item.remediationMaintained).length}/${results.length}`},{id:'monitor-cadence',passed:maximumObservedGap<=maximumCadenceDays,detail:`maximum ${maximumObservedGap} days; allowed ${maximumCadenceDays}`}];const failedChecks=checks.filter(check=>!check.passed).map(check=>check.id);const status=decision==='keep_closed'?(failedChecks.length?'blocked_keep_closed':'stable'):'action_required';const recurrences=results.filter(item=>item.recurred);
    surveillance.push({id,exitReviewId,governancePackId:exit.governancePackId,portfolioItemId:exit.portfolioItemId,title:exit.title,evidenceIds:[...(exit.evidenceIds??[])],targetType:exit.targetType,targetId:exit.targetId,asOf,minimumSnapshots,maximumCadenceDays,maximumObservedGap,snapshots:results,recurrenceCount:recurrences.length,firstRecurrenceAt:recurrences[0]?.asOf??null,review,checks,failedChecks,status});
  }
  return{schemaVersion:'1.0.0',summary:{surveillance:surveillance.length,stable:surveillance.filter(item=>item.status==='stable').length,blockedKeepClosed:surveillance.filter(item=>item.status==='blocked_keep_closed').length,actionRequired:surveillance.filter(item=>item.status==='action_required').length,recurrences:surveillance.reduce((sum,item)=>sum+item.recurrenceCount,0)},surveillance,method:'deterministic verified-exit, lineage, target-stability, remediation, snapshot-coverage, and cadence checks over later Project 25 monitors; the report never reopens an exception or changes a product control'};
}
