const round=value=>Number(value.toFixed(4));
const required=(value,name,max=400)=>{if(typeof value!=='string'||!value.trim()||value.length>max)throw new Error(`${name} must contain 1–${max} characters`);return value.trim()};
const bounded=(value,name,min,max)=>{if(!Number.isFinite(value)||value<min||value>max)throw new Error(`${name} must be between ${min} and ${max}`);return value};
const iso=(value,name)=>{const parsed=new Date(value);if(typeof value!=='string'||Number.isNaN(parsed.valueOf()))throw new Error(`${name} must be an ISO date`);return parsed.toISOString()};

function items(runs){if(!Array.isArray(runs)||runs.length>50)throw new Error('Provide an array of at most 50 product runs');const result=new Map();for(const run of runs){if(!run?.id||!run.ranking)continue;const selected=new Set(run.ranking.portfolio?.selected??[]);for(const item of run.ranking.ranked??[]){if(!selected.has(item.id))continue;const experiments=(run.experiments??[]).filter(x=>x.opportunityId===item.id);result.set(`${run.id}:${item.id}`,{portfolioItemId:`${run.id}:${item.id}`,runId:run.id,runTitle:run.title,opportunityId:item.id,title:item.title,evidenceIds:[...(item.evidenceIds??[])],experimentIds:experiments.map(x=>x.id),decisionIds:experiments.flatMap(x=>x.decision?.id?[x.decision.id]:[])})}}return result}

export function assessAssumptions(runs,input={},now=()=>new Date()){
  if(!Array.isArray(input.assumptions)||!input.assumptions.length||input.assumptions.length>200)throw new Error('Provide 1–200 assumptions');
  const asOf=iso(input.asOf??now().toISOString(),'asOf'),portfolio=items(runs),seen=new Set();
  const assumptions=input.assumptions.map((raw,index)=>{const id=required(raw.id,`Assumption ${index+1} id`,80);if(seen.has(id))throw new Error('Assumption IDs must be unique');seen.add(id);const portfolioItemId=required(raw.portfolioItemId,`${id} portfolioItemId`,240),item=portfolio.get(portfolioItemId);if(!item)throw new Error(`Unknown selected portfolio item: ${portfolioItemId}`);const category=raw.category;if(!['desirability','viability','feasibility','usability','compliance'].includes(category))throw new Error(`${id} has an invalid category`);const status=raw.status??'untested';if(!['untested','testing','supported','refuted'].includes(status))throw new Error(`${id} has an invalid status`);const linkedEvidenceIds=[...new Set(raw.linkedEvidenceIds??[])],linkedExperimentIds=[...new Set(raw.linkedExperimentIds??[])];const badEvidence=linkedEvidenceIds.filter(x=>!item.evidenceIds.includes(x)),badExperiments=linkedExperimentIds.filter(x=>!item.experimentIds.includes(x));if(badEvidence.length)throw new Error(`${id} references evidence outside the opportunity`);if(badExperiments.length)throw new Error(`${id} references experiments outside the opportunity`);const importance=bounded(raw.importance,`${id} importance`,1,5),uncertainty=bounded(raw.uncertainty,`${id} uncertainty`,0,1),reviewBy=iso(raw.reviewBy,`${id} reviewBy`);const overdue=new Date(reviewBy)<new Date(asOf)&&!['supported','refuted'].includes(status);const statusWeight={untested:1,testing:.75,supported:.15,refuted:0}[status];const exposureScore=round(importance*uncertainty*statusWeight+(overdue?.5:0));const evidenceState=linkedEvidenceIds.length||linkedExperimentIds.length?'linked':'unlinked';return{...item,id,statement:required(raw.statement,`${id} statement`,1000),category,status,importance,uncertainty,owner:required(raw.owner,`${id} owner`,120),reviewBy,validationMethod:required(raw.validationMethod,`${id} validationMethod`,1000),linkedEvidenceIds,linkedExperimentIds,evidenceState,overdue,exposureScore}}).sort((a,b)=>b.exposureScore-a.exposureScore||a.id.localeCompare(b.id));
  const categories=Object.fromEntries(['desirability','viability','feasibility','usability','compliance'].map(x=>[x,assumptions.filter(y=>y.category===x).length]));
  return{schemaVersion:'1.0.0',asOf,summary:{assumptions:assumptions.length,untested:assumptions.filter(x=>x.status==='untested').length,testing:assumptions.filter(x=>x.status==='testing').length,supported:assumptions.filter(x=>x.status==='supported').length,refuted:assumptions.filter(x=>x.status==='refuted').length,overdue:assumptions.filter(x=>x.overdue).length,unlinked:assumptions.filter(x=>x.evidenceState==='unlinked').length,categories},validationQueue:assumptions.filter(x=>!['supported','refuted'].includes(x.status)),assumptions,method:'deterministic importance × declared uncertainty × status-weight exposure heuristic; not a probability, prediction, or automatic product decision'}
}
