import test from 'node:test';
import assert from 'node:assert/strict';
import {reviewSunsetOutcomes} from '../src/outcomes.js';

const report = {schemaVersion:'1.0.0',snapshots:[{id:'s',planId:'p',journeyId:'j',releaseId:'rel',portfolioItemId:'r:o',title:'Legacy export',action:'retire',sunsetAt:'2026-06-01T00:00:00Z',asOf:'2026-06-01T00:00:00Z',status:'ready_for_human_sunset',evidenceIds:['f'],shipDecisionIds:['d'],assumptionIds:['a']}]};
const review = (overrides={}) => ({id:'r',snapshotId:'s',reviewedAt:'2026-07-02T00:00:00Z',observationWindowDays:30,support:{baselineContacts:100,observedContacts:105,maximumIncreaseRate:.1},incidents:{critical:0,customerImpacting:0,maximumCritical:0,maximumCustomerImpacting:0},residualTrafficCount:0,economics:{expectedMonthlySavings:1000,observedMonthlySavings:900,minimumRealizationRate:.8,currency:'usd'},rollback:{owner:'Engineering',available:true,testedAt:'2026-06-15T00:00:00Z',procedure:'Restore the archived deployment.',recoveryMinutes:20,maximumRecoveryMinutes:30},correctiveActions:[],decision:{choice:'close',reviewer:'Product council',rationale:'All declared checks passed.',reviewedAt:'2026-07-02T00:00:00Z'},...overrides});

test('closes only a passing human close decision and preserves lineage',()=>{const x=reviewSunsetOutcomes([],report,{reviews:[review()]});assert.equal(x.summary.closed,1);assert.deepEqual(x.reviews[0].evidenceIds,['f']);assert.equal(x.reviews[0].economics.realizationRate,.9)});
test('blocks close before the observation window ends',()=>{const x=reviewSunsetOutcomes([],report,{reviews:[review({reviewedAt:'2026-06-10T00:00:00Z'})]});assert.equal(x.reviews[0].status,'blocked_close');assert.ok(x.reviews[0].failedChecks.includes('observation-window'))});
test('blocks excessive support harm',()=>{const x=reviewSunsetOutcomes([],report,{reviews:[review({support:{baselineContacts:100,observedContacts:130,maximumIncreaseRate:.1}})]});assert.ok(x.reviews[0].failedChecks.includes('customer-support'))});
test('blocks incidents over declared thresholds',()=>{const x=reviewSunsetOutcomes([],report,{reviews:[review({incidents:{critical:1,customerImpacting:1,maximumCritical:0,maximumCustomerImpacting:0}})]});assert.ok(x.reviews[0].failedChecks.includes('incident-impact'))});
test('requires zero residual traffic',()=>{const x=reviewSunsetOutcomes([],report,{reviews:[review({residualTrafficCount:4})]});assert.ok(x.reviews[0].failedChecks.includes('residual-traffic'))});
test('compares observed and expected savings without causal language',()=>{const x=reviewSunsetOutcomes([],report,{reviews:[review({economics:{expectedMonthlySavings:1000,observedMonthlySavings:500,minimumRealizationRate:.8,currency:'USD'}})]});assert.ok(x.reviews[0].failedChecks.includes('savings-realization'));assert.match(x.method,/not causal/)});
test('requires an available rollback within its recovery target',()=>{const x=reviewSunsetOutcomes([],report,{reviews:[review({rollback:{owner:'Eng',available:false,testedAt:'2026-06-15T00:00:00Z',procedure:'Restore.',recoveryMinutes:40,maximumRecoveryMinutes:30}})]});assert.ok(x.reviews[0].failedChecks.includes('reversibility'))});
test('flags overdue corrective actions',()=>{const x=reviewSunsetOutcomes([],report,{reviews:[review({correctiveActions:[{id:'a1',owner:'Support',description:'Resolve complaints.',status:'open',dueAt:'2026-06-20T00:00:00Z'}]})]});assert.equal(x.summary.overdueActions,1);assert.ok(x.reviews[0].failedChecks.includes('corrective-actions'))});
test('keeps extend and restore decisions action-required',()=>{for(const choice of ['extend_monitoring','restore_service']){const x=reviewSunsetOutcomes([],report,{reviews:[review({decision:{choice,reviewer:'Council',rationale:'Human judgment.',reviewedAt:'2026-07-02T00:00:00Z'}})]});assert.equal(x.reviews[0].status,'action_required')}});
test('rejects unknown snapshots, duplicate IDs and invalid decisions',()=>{assert.throws(()=>reviewSunsetOutcomes([],report,{reviews:[review({snapshotId:'x'})]}),/Unknown/);assert.throws(()=>reviewSunsetOutcomes([],report,{reviews:[review(),review()]}),/unique/);assert.throws(()=>reviewSunsetOutcomes([],report,{reviews:[review({decision:{choice:'auto-close',reviewer:'x',rationale:'x',reviewedAt:'2026-07-02T00:00:00Z'}})]}),/invalid/)});
