import assert from 'node:assert/strict';
import test from 'node:test';
import {verifyPlanningPolicyRecovery} from '../src/recovery.js';

const rollout = {id:'rollout-1',proposalId:'change-1',outcomeReviewId:'outcome-1',policyId:'policy-1',fromVersion:'1.0.0',toVersion:'1.1.0',scope:'Connected planning policy',monitors:[{name:'latency',direction:'above',threshold:7},{name:'completion',direction:'below',threshold:.95}],rollback:{targetVersion:'1.0.0',maximumDecisionHours:24,owner:'Planning council'}};
const rolloutReport = {schemaVersion:'1.0.0',asOf:'2027-08-31T00:00:00.000Z',rollouts:[rollout]};
const effectiveness = {id:'effectiveness-1',rolloutId:'rollout-1',experimentId:'experiment-1',status:'action_required',review:{decision:'revert',reviewedAt:'2027-09-01T00:00:00.000Z'}};
const effectivenessReport = {schemaVersion:'1.0.0',asOf:'2027-09-01T00:00:00.000Z',policyReviews:[effectiveness]};
const review = {id:'recovery-1',policyEffectivenessReviewId:'effectiveness-1',initiatedAt:'2027-09-01T12:00:00Z',executionSnapshots:[{id:'e1',observedAt:'2027-09-01T12:00:00Z',percentReverted:50,version:'1.0.0',evidence:'Deployment record one.'},{id:'e2',observedAt:'2027-09-02T00:00:00Z',percentReverted:100,version:'1.0.0',evidence:'Deployment record two.'}],recoverySnapshots:[{id:'r1',observedAt:'2027-09-09T00:00:00Z',version:'1.0.0',monitorValues:[{name:'latency',value:6},{name:'completion',value:.97}],evidence:'Recovery export one.'},{id:'r2',observedAt:'2027-09-16T00:00:00Z',version:'1.0.0',monitorValues:[{name:'latency',value:5.5},{name:'completion',value:.96}],evidence:'Recovery export two.'}],review:{reviewer:'Planning council',decision:'close_reversion',rationale:'Approved target restored and stable.',reviewedAt:'2027-09-16T00:00:00Z'}};
const input = overrides => ({asOf:'2027-09-16T00:00:00Z',minimumRecoveryDays:14,maximumSnapshotGapDays:7,reviews:[{...review,...overrides}]});

test('verifies completed and stable policy recovery with lineage',()=>{const result=verifyPlanningPolicyRecovery([],effectivenessReport,rolloutReport,input());assert.equal(result.status,'verified_recovery');assert.deepEqual(result.sourcePolicyEffectivenessReviewIds,['effectiveness-1']);assert.deepEqual(result.sourcePolicyChangeIds,['change-1']);assert.equal(result.policyRecoveryReviews[0].recoveredVersion,'1.0.0');assert.ok(result.policyRecoveryReviews[0].checks.every(item=>item.passed));});
test('blocks closure without an authorized revert decision',()=>{const report={...effectivenessReport,policyReviews:[{...effectiveness,review:{...effectiveness.review,decision:'adjust'}}]};assert.equal(verifyPlanningPolicyRecovery([],report,rolloutReport,input()).status,'blocked_close');});
test('blocks initiation after rollback decision SLA',()=>{const executionSnapshots=review.executionSnapshots.map((item,index)=>({...item,observedAt:index?'2027-09-03T00:00:00Z':'2027-09-02T01:00:00Z'}));const recoverySnapshots=review.recoverySnapshots.map((item,index)=>({...item,observedAt:index?'2027-09-17T00:00:00Z':'2027-09-10T00:00:00Z'}));const value={...input({initiatedAt:'2027-09-02T01:00:00Z',executionSnapshots,recoverySnapshots,review:{...review.review,reviewedAt:'2027-09-17T00:00:00Z'}}),asOf:'2027-09-17T00:00:00Z'};assert.equal(verifyPlanningPolicyRecovery([],effectivenessReport,rolloutReport,value).status,'blocked_close');});
test('blocks incomplete reversion execution',()=>assert.equal(verifyPlanningPolicyRecovery([],effectivenessReport,rolloutReport,input({executionSnapshots:[review.executionSnapshots[0]]})).status,'blocked_close'));
test('blocks snapshots on the wrong version',()=>{const recoverySnapshots=review.recoverySnapshots.map((item,index)=>index?{...item,version:'1.1.0'}:item);assert.equal(verifyPlanningPolicyRecovery([],effectivenessReport,rolloutReport,input({recoverySnapshots})).status,'blocked_close');});
test('blocks an incomplete recovery window',()=>assert.equal(verifyPlanningPolicyRecovery([],effectivenessReport,rolloutReport,{...input(),minimumRecoveryDays:15}).status,'blocked_close'));
test('blocks excessive recovery gaps',()=>assert.equal(verifyPlanningPolicyRecovery([],effectivenessReport,rolloutReport,{...input(),maximumSnapshotGapDays:6}).status,'blocked_close'));
test('blocks upper-bound monitor regression',()=>{const recoverySnapshots=review.recoverySnapshots.map((item,index)=>index?{...item,monitorValues:[{name:'latency',value:8},{name:'completion',value:.96}]}:item);assert.equal(verifyPlanningPolicyRecovery([],effectivenessReport,rolloutReport,input({recoverySnapshots})).status,'blocked_close');});
test('blocks lower-bound monitor regression',()=>{const recoverySnapshots=review.recoverySnapshots.map((item,index)=>index?{...item,monitorValues:[{name:'latency',value:6},{name:'completion',value:.9}]}:item);assert.equal(verifyPlanningPolicyRecovery([],effectivenessReport,rolloutReport,input({recoverySnapshots})).status,'blocked_close');});
test('keeps monitoring and escalation as human actions',()=>{for(const decision of ['continue_monitoring','escalate'])assert.equal(verifyPlanningPolicyRecovery([],effectivenessReport,rolloutReport,input({review:{...review.review,decision}})).status,'action_required');});
test('rejects missing, unknown, or duplicate monitor values',()=>{const recoverySnapshots=review.recoverySnapshots.map((item,index)=>index?{...item,monitorValues:[{name:'unknown',value:1},{name:'completion',value:.96}]}:item);assert.throws(()=>verifyPlanningPolicyRecovery([],effectivenessReport,rolloutReport,input({recoverySnapshots})),/declared/);});
test('rejects recovery snapshots before completion',()=>{const recoverySnapshots=[{...review.recoverySnapshots[0],observedAt:'2027-09-01T20:00:00Z'},review.recoverySnapshots[1]];assert.throws(()=>verifyPlanningPolicyRecovery([],effectivenessReport,rolloutReport,input({recoverySnapshots})),/follow completed/);});
test('rejects duplicate reviews and source assessments',()=>{assert.throws(()=>verifyPlanningPolicyRecovery([],effectivenessReport,rolloutReport,{...input(),reviews:[review,review]}),/IDs must be unique/);assert.throws(()=>verifyPlanningPolicyRecovery([],effectivenessReport,rolloutReport,{...input(),reviews:[review,{...review,id:'recovery-2'}]}),/only one/);});
test('rejects unknown lineage and missing rollback controls',()=>{assert.throws(()=>verifyPlanningPolicyRecovery([],effectivenessReport,rolloutReport,input({policyEffectivenessReviewId:'missing'})),/Project 36/);const report={...rolloutReport,rollouts:[{...rollout,rollback:undefined}]};assert.throws(()=>verifyPlanningPolicyRecovery([],effectivenessReport,report,input()),/rollback/);});
test('rejects malformed reports and invalid bounds',()=>{assert.throws(()=>verifyPlanningPolicyRecovery([],{},rolloutReport,input()),/Project 36/);assert.throws(()=>verifyPlanningPolicyRecovery([],effectivenessReport,{},input()),/Project 35/);assert.throws(()=>verifyPlanningPolicyRecovery([],effectivenessReport,rolloutReport,{...input(),minimumRecoveryDays:0}),/1 to 90/);});
